server {
  listen 80;

  client_max_body_size 10m;
  root /public/;

  gzip on;
  gzip_types text/plain text/css application/javascript image/svg+xml;
  keepalive_timeout 65;

  location /image/ {
    try_files $uri @app;
  }

  location @app {
    proxy_set_header Host $host;
    proxy_pass http://app:8080;
  }

  location / {
    proxy_set_header Host $host;
    proxy_pass http://app:8080;
  }
}
